// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(clipboard_coreFFI)
import clipboard_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_clipboard_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_clipboard_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureClipboardCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * The single FFI entry point: pairing lifecycle, clipboard session, and history.
 */
public protocol CoreHandleProtocol: AnyObject, Sendable {

    /**
     * Snapshot of the local history store (most recent last).
     */
    func history() throws  -> [FfiHistoryItem]

    /**
     * Raw encoded bytes of an image history item.
     */
    func historyImageBytes(id: String) throws  -> Data

    /**
     * True when `hash` (see the shared `text_hash` contract) matches a
     * recently sent or applied text clip; false when no session is live.
     */
    func isEcho(hash: String)  -> Bool

    /**
     * Publishes a fresh pairing offer against `server_url` and returns the QR
     * payload JSON the host must display. The peer's arrival is announced via
     * `on_status(SasReady)` / `pair_poll`.
     *
     * `server_url` is validated in core (`wss://`; `ws://` only in debug
     * builds) before any network I/O.
     */
    func pairBegin(serverUrl: String) throws  -> String

    /**
     * Cancels an in-flight pairing offer or pending SAS confirmation. A
     * durable pairing is never touched.
     */
    func pairCancel() throws

    /**
     * Claims the offer pinned in `qr_payload` (the scanned QR JSON) and
     * returns the SAS the user must compare with the offerer's display.
     */
    func pairClaim(qrPayload: String) throws  -> String

    /**
     * Confirms the user-verified SAS, durably records the pairing, joins the
     * relay, and starts the live session.
     */
    func pairConfirm(sas: String) throws

    /**
     * Loads the durable pairing record (app restart path). Returns `true`
     * when a record exists; `start()` then connects the live session.
     */
    func pairLoad() throws  -> Bool

    /**
     * Point-in-time pairing state snapshot.
     */
    func pairPoll()  -> PairingSnapshot

    /**
     * Stops and joins the session and dispatcher, runs the T5 generation
     * reset, then installs a fresh empty dispatcher/runtime. On success the
     * handle is `ReadyUnpaired` and can immediately pair again.
     */
    func resetPairing() throws

    /**
     * Queues an image clip (encoded bytes, ≤10 MiB) for the peer.
     */
    func sendImage(bytes: Data) throws  -> UInt64

    /**
     * Queues a text clip for the peer; returns its sequence number once the
     * frame is written to the relay. Full queue → typed `QueueFull`.
     */
    func sendText(text: String) throws  -> UInt64

    /**
     * Stops and joins the session and dispatcher, then shuts the runtime
     * down. The handle is terminal afterwards; every call fails `Shutdown`.
     */
    func shutdown() throws

    /**
     * Joins the relay with the durable pairing record and starts the live
     * session (app restart path; pairing flows connect automatically).
     */
    func start() throws

}
/**
 * The single FFI entry point: pairing lifecycle, clipboard session, and history.
 */
open class CoreHandle: CoreHandleProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_clipboard_core_fn_clone_corehandle(self.pointer, $0) }
    }
    /**
     * Opens (or creates) the core state under `data_dir` and starts the
     * bounded FIFO dispatcher on a fresh runtime.
     */
public convenience init(dataDir: String, callbacks: CoreCallbacks)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_constructor_corehandle_new(
        FfiConverterString.lower(dataDir),
        FfiConverterCallbackInterfaceCoreCallbacks_lower(callbacks),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_clipboard_core_fn_free_corehandle(pointer, $0) }
    }




    /**
     * Snapshot of the local history store (most recent last).
     */
open func history()throws  -> [FfiHistoryItem]  {
    return try  FfiConverterSequenceTypeFfiHistoryItem.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_method_corehandle_history(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Raw encoded bytes of an image history item.
     */
open func historyImageBytes(id: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_method_corehandle_history_image_bytes(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}

    /**
     * True when `hash` (see the shared `text_hash` contract) matches a
     * recently sent or applied text clip; false when no session is live.
     */
open func isEcho(hash: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_clipboard_core_fn_method_corehandle_is_echo(self.uniffiClonePointer(),
        FfiConverterString.lower(hash),$0
    )
})
}

    /**
     * Publishes a fresh pairing offer against `server_url` and returns the QR
     * payload JSON the host must display. The peer's arrival is announced via
     * `on_status(SasReady)` / `pair_poll`.
     *
     * `server_url` is validated in core (`wss://`; `ws://` only in debug
     * builds) before any network I/O.
     */
open func pairBegin(serverUrl: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_method_corehandle_pair_begin(self.uniffiClonePointer(),
        FfiConverterString.lower(serverUrl),$0
    )
})
}

    /**
     * Cancels an in-flight pairing offer or pending SAS confirmation. A
     * durable pairing is never touched.
     */
open func pairCancel()throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_method_corehandle_pair_cancel(self.uniffiClonePointer(),$0
    )
}
}

    /**
     * Claims the offer pinned in `qr_payload` (the scanned QR JSON) and
     * returns the SAS the user must compare with the offerer's display.
     */
open func pairClaim(qrPayload: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_method_corehandle_pair_claim(self.uniffiClonePointer(),
        FfiConverterString.lower(qrPayload),$0
    )
})
}

    /**
     * Confirms the user-verified SAS, durably records the pairing, joins the
     * relay, and starts the live session.
     */
open func pairConfirm(sas: String)throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_method_corehandle_pair_confirm(self.uniffiClonePointer(),
        FfiConverterString.lower(sas),$0
    )
}
}

    /**
     * Loads the durable pairing record (app restart path). Returns `true`
     * when a record exists; `start()` then connects the live session.
     */
open func pairLoad()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_method_corehandle_pair_load(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Point-in-time pairing state snapshot.
     */
open func pairPoll() -> PairingSnapshot  {
    return try!  FfiConverterTypePairingSnapshot_lift(try! rustCall() {
    uniffi_clipboard_core_fn_method_corehandle_pair_poll(self.uniffiClonePointer(),$0
    )
})
}

    /**
     * Stops and joins the session and dispatcher, runs the T5 generation
     * reset, then installs a fresh empty dispatcher/runtime. On success the
     * handle is `ReadyUnpaired` and can immediately pair again.
     */
open func resetPairing()throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_method_corehandle_reset_pairing(self.uniffiClonePointer(),$0
    )
}
}

    /**
     * Queues an image clip (encoded bytes, ≤10 MiB) for the peer.
     */
open func sendImage(bytes: Data)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_method_corehandle_send_image(self.uniffiClonePointer(),
        FfiConverterData.lower(bytes),$0
    )
})
}

    /**
     * Queues a text clip for the peer; returns its sequence number once the
     * frame is written to the relay. Full queue → typed `QueueFull`.
     */
open func sendText(text: String)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_method_corehandle_send_text(self.uniffiClonePointer(),
        FfiConverterString.lower(text),$0
    )
})
}

    /**
     * Stops and joins the session and dispatcher, then shuts the runtime
     * down. The handle is terminal afterwards; every call fails `Shutdown`.
     */
open func shutdown()throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_method_corehandle_shutdown(self.uniffiClonePointer(),$0
    )
}
}

    /**
     * Joins the relay with the durable pairing record and starts the live
     * session (app restart path; pairing flows connect automatically).
     */
open func start()throws   {try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_clipboard_core_fn_method_corehandle_start(self.uniffiClonePointer(),$0
    )
}
}


}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreHandle: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = CoreHandle

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> CoreHandle {
        return CoreHandle(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: CoreHandle) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreHandle {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: CoreHandle, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreHandle_lift(_ pointer: UnsafeMutableRawPointer) throws -> CoreHandle {
    return try FfiConverterTypeCoreHandle.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreHandle_lower(_ value: CoreHandle) -> UnsafeMutableRawPointer {
    return FfiConverterTypeCoreHandle.lower(value)
}




/**
 * One authenticated clipboard item delivered to the host shell.
 */
public struct FfiClipItem {
    public var id: String
    public var tsMs: Int64
    public var seq: UInt64
    public var content: FfiClipContent

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, tsMs: Int64, seq: UInt64, content: FfiClipContent) {
        self.id = id
        self.tsMs = tsMs
        self.seq = seq
        self.content = content
    }
}

#if compiler(>=6)
extension FfiClipItem: Sendable {}
#endif


extension FfiClipItem: Equatable, Hashable {
    public static func ==(lhs: FfiClipItem, rhs: FfiClipItem) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.tsMs != rhs.tsMs {
            return false
        }
        if lhs.seq != rhs.seq {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(tsMs)
        hasher.combine(seq)
        hasher.combine(content)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiClipItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiClipItem {
        return
            try FfiClipItem(
                id: FfiConverterString.read(from: &buf),
                tsMs: FfiConverterInt64.read(from: &buf),
                seq: FfiConverterUInt64.read(from: &buf),
                content: FfiConverterTypeFfiClipContent.read(from: &buf)
        )
    }

    public static func write(_ value: FfiClipItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterInt64.write(value.tsMs, into: &buf)
        FfiConverterUInt64.write(value.seq, into: &buf)
        FfiConverterTypeFfiClipContent.write(value.content, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClipItem_lift(_ buf: RustBuffer) throws -> FfiClipItem {
    return try FfiConverterTypeFfiClipItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClipItem_lower(_ value: FfiClipItem) -> RustBuffer {
    return FfiConverterTypeFfiClipItem.lower(value)
}


/**
 * One history entry as shown by the host.
 */
public struct FfiHistoryItem {
    public var id: String
    public var tsMs: Int64
    public var kind: FfiHistoryKind
    public var source: FfiHistorySource

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, tsMs: Int64, kind: FfiHistoryKind, source: FfiHistorySource) {
        self.id = id
        self.tsMs = tsMs
        self.kind = kind
        self.source = source
    }
}

#if compiler(>=6)
extension FfiHistoryItem: Sendable {}
#endif


extension FfiHistoryItem: Equatable, Hashable {
    public static func ==(lhs: FfiHistoryItem, rhs: FfiHistoryItem) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.tsMs != rhs.tsMs {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.source != rhs.source {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(tsMs)
        hasher.combine(kind)
        hasher.combine(source)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiHistoryItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiHistoryItem {
        return
            try FfiHistoryItem(
                id: FfiConverterString.read(from: &buf),
                tsMs: FfiConverterInt64.read(from: &buf),
                kind: FfiConverterTypeFfiHistoryKind.read(from: &buf),
                source: FfiConverterTypeFfiHistorySource.read(from: &buf)
        )
    }

    public static func write(_ value: FfiHistoryItem, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterInt64.write(value.tsMs, into: &buf)
        FfiConverterTypeFfiHistoryKind.write(value.kind, into: &buf)
        FfiConverterTypeFfiHistorySource.write(value.source, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHistoryItem_lift(_ buf: RustBuffer) throws -> FfiHistoryItem {
    return try FfiConverterTypeFfiHistoryItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHistoryItem_lower(_ value: FfiHistoryItem) -> RustBuffer {
    return FfiConverterTypeFfiHistoryItem.lower(value)
}


/**
 * Typed errors crossing the FFI boundary.
 *
 * `QueueFull` is the typed backpressure signal: the bounded dispatcher queue
 * is full and the host must retry later instead of dropping the clip.
 */
public enum CoreError: Swift.Error {



    case InvalidInput(String
    )
    case Busy
    case NotPaired
    case QueueFull
    case Transport(String
    )
    case SasMismatch
    case Shutdown
    case Internal(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreError: FfiConverterRustBuffer {
    typealias SwiftType = CoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .InvalidInput(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .Busy
        case 3: return .NotPaired
        case 4: return .QueueFull
        case 5: return .Transport(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .SasMismatch
        case 7: return .Shutdown
        case 8: return .Internal(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreError, into buf: inout [UInt8]) {
        switch value {





        case let .InvalidInput(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)


        case .Busy:
            writeInt(&buf, Int32(2))


        case .NotPaired:
            writeInt(&buf, Int32(3))


        case .QueueFull:
            writeInt(&buf, Int32(4))


        case let .Transport(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)


        case .SasMismatch:
            writeInt(&buf, Int32(6))


        case .Shutdown:
            writeInt(&buf, Int32(7))


        case let .Internal(v1):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(v1, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lift(_ buf: RustBuffer) throws -> CoreError {
    return try FfiConverterTypeCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lower(_ value: CoreError) -> RustBuffer {
    return FfiConverterTypeCoreError.lower(value)
}


extension CoreError: Equatable, Hashable {}




extension CoreError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Typed lifecycle status pushed to the host.
 */

public enum CoreStatus {

    /**
     * No durable pairing; ready to pair.
     */
    case readyUnpaired
    /**
     * Pairing offer published; waiting for the peer to claim.
     */
    case offering
    /**
     * Peer bundle arrived; the SAS must be confirmed by the user.
     */
    case sasReady
    /**
     * Joining the relay with the durable pairing record.
     */
    case connecting
    /**
     * Live session established (also fired after a successful reconnect).
     */
    case connected
    /**
     * Transport dropped; automatic reconnect with backoff is in progress.
     */
    case reconnecting
    /**
     * Live session ended; `start()` reconnects while the pairing survives.
     */
    case disconnected
    /**
     * Non-fatal failure (for example a rejected clipboard callback).
     */
    case error(message: String
    )
}


#if compiler(>=6)
extension CoreStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreStatus: FfiConverterRustBuffer {
    typealias SwiftType = CoreStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .readyUnpaired

        case 2: return .offering

        case 3: return .sasReady

        case 4: return .connecting

        case 5: return .connected

        case 6: return .reconnecting

        case 7: return .disconnected

        case 8: return .error(message: try FfiConverterString.read(from: &buf)
        )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreStatus, into buf: inout [UInt8]) {
        switch value {


        case .readyUnpaired:
            writeInt(&buf, Int32(1))


        case .offering:
            writeInt(&buf, Int32(2))


        case .sasReady:
            writeInt(&buf, Int32(3))


        case .connecting:
            writeInt(&buf, Int32(4))


        case .connected:
            writeInt(&buf, Int32(5))


        case .reconnecting:
            writeInt(&buf, Int32(6))


        case .disconnected:
            writeInt(&buf, Int32(7))


        case let .error(message):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(message, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreStatus_lift(_ buf: RustBuffer) throws -> CoreStatus {
    return try FfiConverterTypeCoreStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreStatus_lower(_ value: CoreStatus) -> RustBuffer {
    return FfiConverterTypeCoreStatus.lower(value)
}


extension CoreStatus: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Clipboard payload crossing the FFI boundary.
 */

public enum FfiClipContent {

    case text(text: String
    )
    case image(bytes: Data
    )
}


#if compiler(>=6)
extension FfiClipContent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiClipContent: FfiConverterRustBuffer {
    typealias SwiftType = FfiClipContent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiClipContent {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .text(text: try FfiConverterString.read(from: &buf)
        )

        case 2: return .image(bytes: try FfiConverterData.read(from: &buf)
        )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiClipContent, into buf: inout [UInt8]) {
        switch value {


        case let .text(text):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(text, into: &buf)


        case let .image(bytes):
            writeInt(&buf, Int32(2))
            FfiConverterData.write(bytes, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClipContent_lift(_ buf: RustBuffer) throws -> FfiClipContent {
    return try FfiConverterTypeFfiClipContent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiClipContent_lower(_ value: FfiClipContent) -> RustBuffer {
    return FfiConverterTypeFfiClipContent.lower(value)
}


extension FfiClipContent: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * History payload kind; image bytes are fetched via `history_image_bytes`.
 */

public enum FfiHistoryKind {

    case text(content: String
    )
    case image
}


#if compiler(>=6)
extension FfiHistoryKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiHistoryKind: FfiConverterRustBuffer {
    typealias SwiftType = FfiHistoryKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiHistoryKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .text(content: try FfiConverterString.read(from: &buf)
        )

        case 2: return .image

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiHistoryKind, into buf: inout [UInt8]) {
        switch value {


        case let .text(content):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(content, into: &buf)


        case .image:
            writeInt(&buf, Int32(2))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHistoryKind_lift(_ buf: RustBuffer) throws -> FfiHistoryKind {
    return try FfiConverterTypeFfiHistoryKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHistoryKind_lower(_ value: FfiHistoryKind) -> RustBuffer {
    return FfiConverterTypeFfiHistoryKind.lower(value)
}


extension FfiHistoryKind: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * History provenance, mirroring the T4 store sources.
 */

public enum FfiHistorySource {

    case local
    case remote
    case remoteDeferred
}


#if compiler(>=6)
extension FfiHistorySource: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiHistorySource: FfiConverterRustBuffer {
    typealias SwiftType = FfiHistorySource

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiHistorySource {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .local

        case 2: return .remote

        case 3: return .remoteDeferred

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiHistorySource, into buf: inout [UInt8]) {
        switch value {


        case .local:
            writeInt(&buf, Int32(1))


        case .remote:
            writeInt(&buf, Int32(2))


        case .remoteDeferred:
            writeInt(&buf, Int32(3))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHistorySource_lift(_ buf: RustBuffer) throws -> FfiHistorySource {
    return try FfiConverterTypeFfiHistorySource.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiHistorySource_lower(_ value: FfiHistorySource) -> RustBuffer {
    return FfiConverterTypeFfiHistorySource.lower(value)
}


extension FfiHistorySource: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Host decision for a mailbox (or stale-live) clip.
 */

public enum MailboxDisposition {

    case applied
    case deferred
}


#if compiler(>=6)
extension MailboxDisposition: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMailboxDisposition: FfiConverterRustBuffer {
    typealias SwiftType = MailboxDisposition

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MailboxDisposition {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .applied

        case 2: return .deferred

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MailboxDisposition, into buf: inout [UInt8]) {
        switch value {


        case .applied:
            writeInt(&buf, Int32(1))


        case .deferred:
            writeInt(&buf, Int32(2))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMailboxDisposition_lift(_ buf: RustBuffer) throws -> MailboxDisposition {
    return try FfiConverterTypeMailboxDisposition.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMailboxDisposition_lower(_ value: MailboxDisposition) -> RustBuffer {
    return FfiConverterTypeMailboxDisposition.lower(value)
}


extension MailboxDisposition: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Point-in-time pairing state for hosts that prefer polling over callbacks.
 */

public enum PairingSnapshot {

    case unpaired
    case offering(qrJson: String
    )
    case sasReady(sas: String
    )
    case paired(roomId: String
    )
}


#if compiler(>=6)
extension PairingSnapshot: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePairingSnapshot: FfiConverterRustBuffer {
    typealias SwiftType = PairingSnapshot

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PairingSnapshot {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .unpaired

        case 2: return .offering(qrJson: try FfiConverterString.read(from: &buf)
        )

        case 3: return .sasReady(sas: try FfiConverterString.read(from: &buf)
        )

        case 4: return .paired(roomId: try FfiConverterString.read(from: &buf)
        )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PairingSnapshot, into buf: inout [UInt8]) {
        switch value {


        case .unpaired:
            writeInt(&buf, Int32(1))


        case let .offering(qrJson):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(qrJson, into: &buf)


        case let .sasReady(sas):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(sas, into: &buf)


        case let .paired(roomId):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(roomId, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairingSnapshot_lift(_ buf: RustBuffer) throws -> PairingSnapshot {
    return try FfiConverterTypePairingSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePairingSnapshot_lower(_ value: PairingSnapshot) -> RustBuffer {
    return FfiConverterTypePairingSnapshot.lower(value)
}


extension PairingSnapshot: Equatable, Hashable {}









/**
 * Typed callback surface implemented by the platform shell.
 *
 * Implementations must be thread-safe; callbacks fire from dispatcher worker
 * threads, never while the handle holds its state lock, so hosts may call
 * back into the handle (for example `pair_poll`) from any callback.
 */
public protocol CoreCallbacks: AnyObject, Sendable {

    /**
     * Fresh live clip; core has already durably recorded history.
     */
    func onClip(item: FfiClipItem) throws

    /**
     * Mailbox or stale clip; the returned disposition decides whether the
     * history entry is promoted from `RemoteDeferred` to `Remote`.
     */
    func onMailboxClip(item: FfiClipItem) throws  -> MailboxDisposition

    /**
     * Typed lifecycle status transition.
     */
    func onStatus(status: CoreStatus)

}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceCoreCallbacks {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceCoreCallbacks] = [UniffiVTableCallbackInterfaceCoreCallbacks(
        onClip: { (
            uniffiHandle: UInt64,
            item: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCoreCallbacks.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onClip(
                     item: try FfiConverterTypeFfiClipItem_lift(item)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeCoreError_lower
            )
        },
        onMailboxClip: { (
            uniffiHandle: UInt64,
            item: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> MailboxDisposition in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCoreCallbacks.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onMailboxClip(
                     item: try FfiConverterTypeFfiClipItem_lift(item)
                )
            }


            let writeReturn = { uniffiOutReturn.pointee = FfiConverterTypeMailboxDisposition_lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeCoreError_lower
            )
        },
        onStatus: { (
            uniffiHandle: UInt64,
            status: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceCoreCallbacks.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onStatus(
                     status: try FfiConverterTypeCoreStatus_lift(status)
                )
            }


            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceCoreCallbacks.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface CoreCallbacks: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitCoreCallbacks() {
    uniffi_clipboard_core_fn_init_callback_vtable_corecallbacks(UniffiCallbackInterfaceCoreCallbacks.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceCoreCallbacks {
    fileprivate static let handleMap = UniffiHandleMap<CoreCallbacks>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceCoreCallbacks : FfiConverter {
    typealias SwiftType = CoreCallbacks
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceCoreCallbacks_lift(_ handle: UInt64) throws -> CoreCallbacks {
    return try FfiConverterCallbackInterfaceCoreCallbacks.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceCoreCallbacks_lower(_ v: CoreCallbacks) -> UInt64 {
    return FfiConverterCallbackInterfaceCoreCallbacks.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiHistoryItem: FfiConverterRustBuffer {
    typealias SwiftType = [FfiHistoryItem]

    public static func write(_ value: [FfiHistoryItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiHistoryItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiHistoryItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiHistoryItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiHistoryItem.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_clipboard_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_history() != 57692) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_history_image_bytes() != 55220) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_is_echo() != 21458) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_pair_begin() != 10858) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_pair_cancel() != 56098) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_pair_claim() != 21450) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_pair_confirm() != 28389) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_pair_load() != 62077) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_pair_poll() != 51350) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_reset_pairing() != 56390) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_send_image() != 34410) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_send_text() != 55285) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_shutdown() != 34459) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corehandle_start() != 55175) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_constructor_corehandle_new() != 49618) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corecallbacks_on_clip() != 38845) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corecallbacks_on_mailbox_clip() != 28752) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipboard_core_checksum_method_corecallbacks_on_status() != 22908) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitCoreCallbacks()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureClipboardCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all